//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_StokTakip.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GirisCikis1
    {
        public int FisNo { get; set; }
        public int DepoID { get; set; }
        public int StokID { get; set; }
        public decimal Miktar { get; set; }
        public string Birim { get; set; }
        public string İslem { get; set; }
        public System.DateTime Tarih { get; set; }
        public int KullaniciID { get; set; }
    
        public virtual Depo1 Depo1 { get; set; }
        public virtual Kullanici1 Kullanici1 { get; set; }
        public virtual Stok1 Stok1 { get; set; }
    }
}
