//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_StokTakip.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StokDbEntities : DbContext
    {
        public StokDbEntities()
            : base("name=StokDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Depo1> Depo1 { get; set; }
        public virtual DbSet<GirisCikis1> GirisCikis1 { get; set; }
        public virtual DbSet<Kullanici1> Kullanici1 { get; set; }
        public virtual DbSet<Stok1> Stok1 { get; set; }
        public virtual DbSet<StokLog> StokLogs { get; set; }
        public virtual DbSet<ELMAH_Error> ELMAH_Error { get; set; }
    }
}
