//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_StokTakip.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class StokLog
    {
        public int ID { get; set; }
        public string StokAdi { get; set; }
        public Nullable<int> StokMiktar { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> IslemSaati { get; set; }
        public string IslemTuru { get; set; }
    }
}
